### ISSUE TITLE
Use GUIDs for custom IDs

### ISSUE THREAD

**Issue by wendellmva** [benne/gulp-mongodb-data#2]
I've been using this tool for a while great tool! I use guid for _id, it worked find before but I think you added a check for objectId which of course breaks my gulp seed task. Is there a way to disable this check?

**Comment by benne** [comment]
The possibility to use simple strings as _id totally skipped my mind (mostly because this wasn't an issue with our own setup), but I think it is a great idea and easy to implement, so I pushed a new version to npm, 2.1.0, with the new option 'idAsObjectID' - when set to false, it won't try to convert strings into ObjectIDs, while retaining backwards compatibility by using true as the default value.

Let me hear if this solves your problem.

**Comment by benne** [comment]
I'll let this issue sit for a few more days, and then it will be closed if there is no more comments. The requested functionality should be available in 2.1.0.

**Comment by benne** [comment]
Closing the issue for now.

**Comment by wendellmva** [comment]
I sat down to today to tackle the issue and what you know you fixed it. Thanks man its greatly appreciated. Ill see if it solves my problem ill let you know
